defaults:
  - _self_
  - data: default
  - model: default
  - optimizer: optim
  - trainer: train
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:  
  output_subdir: null  
  run:  
    dir: .
exp_dir:
exp_name: LRW_words_classification
gpus: 
# slurm_job_id:
# file_path: 
# ckpt_path:
pretrained_model_path: 